// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class AttributeWithBlame {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AttributeWithBlame {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAttributeWithBlame(bb:flatbuffers.ByteBuffer, obj?:AttributeWithBlame):AttributeWithBlame {
  return (obj || new AttributeWithBlame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAttributeWithBlame(bb:flatbuffers.ByteBuffer, obj?:AttributeWithBlame):AttributeWithBlame {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AttributeWithBlame()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

value():string|null
value(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
value(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

blame():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startAttributeWithBlame(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, keyOffset, 0);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, valueOffset, 0);
}

static addBlame(builder:flatbuffers.Builder, blame:number) {
  builder.addFieldInt32(2, blame, 0);
}

static endAttributeWithBlame(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAttributeWithBlame(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset, valueOffset:flatbuffers.Offset, blame:number):flatbuffers.Offset {
  AttributeWithBlame.startAttributeWithBlame(builder);
  AttributeWithBlame.addKey(builder, keyOffset);
  AttributeWithBlame.addValue(builder, valueOffset);
  AttributeWithBlame.addBlame(builder, blame);
  return AttributeWithBlame.endAttributeWithBlame(builder);
}
}
